// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TamaDotNet.Server.Data;

#nullable disable

namespace TamaDotNet.Server.Migrations
{
    [DbContext(typeof(TamaDbContext))]
    partial class TamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TamaDotNet.Shared.Data.QuoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("TamaDotNet.Shared.Data.TamaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Hunger")
                        .HasColumnType("int");

                    b.Property<int>("Hygiene")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastShower")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastFed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lastMood")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tamas");
                });

            modelBuilder.Entity("TamaDotNet.Shared.Data.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("TamaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TamaId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TamaDotNet.Shared.Data.UserModel", b =>
                {
                    b.HasOne("TamaDotNet.Shared.Data.TamaModel", "Tama")
                        .WithOne("User")
                        .HasForeignKey("TamaDotNet.Shared.Data.UserModel", "TamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tama");
                });

            modelBuilder.Entity("TamaDotNet.Shared.Data.TamaModel", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
